DROP TABLE IF EXISTS users;
CREATE TABLE IF NOT EXISTS users (
    user_id TEXT PRIMARY KEY,
    email VARCHAR(100) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS searches;
CREATE TABLE IF NOT EXISTS searches (
    search_id TEXT PRIMARY KEY,
    user_id TEXT REFERENCES users(user_id),
    search_result TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
