DROP TABLE IF EXISTS searches;
DROP TABLE IF EXISTS users;
CREATE TABLE IF NOT EXISTS users (
    user_id TEXT PRIMARY KEY,
    email VARCHAR(100) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS searches (
    search_id TEXT PRIMARY KEY,
    user_id TEXT REFERENCES users(user_id),
    search_topic TEXT NOT NULL,
    search_result TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
